title: Yang Hou
first_name: Yang
last_name: Hou
email: YOUR_EMAIL
description: Academic homepage of Yang Hou

url: "https://ironsword666.github.io"
baseurl: ""
theme_color: blue
enable_darkmode: true
navbar_fixed: true
footer_fixed: true
font: Inter

include:
  - _pages

profile:
  align: right
  image: avatar.jpg
  image_circular: false

socials:
  scholar_userid: 1G-PhgwAAAAJ
  github_username: ironsword666

collections:
  news:
    output: true
  projects:
    output: true

third_party_libraries:
  google_fonts:
    url:
      fonts: https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-scholar

scholar:
  first_name: [Yang]
  last_name: [Hou]
  source: _bibliography
  bibliography: papers.bib
  bibliography_template: bib
  sort_by: year
  order: descending
  group_by: year
